from flask import Blueprint, request
from init import db
from datetime import date

from models.states import State


states_bp = Blueprint('states', __name__, url_prefix='/states')

# The GET routes endpoint
@states_bp.route('/', methods=['GET'])
def get_states():
    # get all the cards from the database table
    states_list = State.query.all()
    # Convert the cards from the database into a JSON format and store them in result
    # result = cards_schema.dump(cards_list)
    # return the data in JSON format
    #return jsonify(result)
    return "List of states retrieved"

# The POST route endpoint
@states_bp.route('/', methods=['POST'])
def create_states():
    # #Create a new card
    # card_fields = card_schema.load(request.json)

    # new_card = Card()
    # new_card.title = card_fields["title"]
    # new_card.description = card_fields["description"]
    # new_card.status = card_fields["status"]
    # new_card.priority = card_fields["priority"]
    # # not taken from the request, generated by the server
    # new_card.date = date.today()
    # # add to the database and commit
    # db.session.add(new_card)
    # db.session.commit()
    # #return the card in the response
    # return jsonify(card_schema.dump(new_card))
    return "State created"